id: null
base_encoder: null
dataset_name: null
annotation_name: null
data_index_list: null

dataset_size: null
batch_size: 256
img_size: 64
num_channels: 8
num_classes: 6

label_mode: multilabel
freeze_encoder: true

proj_layers: 0
head_layers: []

train_size: 0.8
epochs: 100
epochs_trained: 0

optimizer: ADAM
learning_rate: 0.0001
weight_decay: 0.0001
dropout: 0.3

pos_weight: null

init_time: null
status: 0

thresholds: null
best_epoch: 0
